source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NNAvatarView_Example', :exclusive => true do
  pod "NNAvatarView", :path => "../"
end

target 'NNAvatarView_Tests', :exclusive => true do
  pod "NNAvatarView", :path => "../"

  
end
